service: pillbox
frameworkVersion: '3'

# load variables from .env file
useDotenv: true

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!./**'
    - 'src/**'
    - '!src/**/*.pyc'

functions:
  pillBoxEcho:
    handler: src/handler.echo
    events:
      - http:
          path: /pillbox/echo
          method: get
          integration: lambda-proxy
          authorizer:
            arn: ${env:COGNITO_ARN}
  pillBoxFindPillByImage:
    handler: src/pill_image_handler.find_pill_by_image
    events:
      - http:
          path: /pillbox/findByImage
          method: post
          integration: lambda-proxy
          authorizer:
            arn: ${env:COGNITO_ARN}
  pillBoxMangum:
    module: src/mangum
    handler: pillbox_mangum.handler
    events:
      - http:
          path: /pillbox/{proxy+}
          method: any
          integration: lambda-proxy
          authorizer:
            arn: ${env:COGNITO_ARN}
      - http:
          path: /pillbox
          method: any
          integration: lambda-proxy
          authorizer:
            arn: ${env:COGNITO_ARN}
    environment:
      ${file(.env.yml)}